// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your services apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await services.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs8S4CXKNWEnfnUGj1_3FTPQXWzgV9fPs',
    appId: '1:1090632603312:android:18a099181ebe08c632cd75',
    messagingSenderId: '1090632603312',
    projectId: 'uninexus-1aea7',
    storageBucket: 'uninexus-1aea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwyamDPlp0Gf9qh0cO0LeEEWgUhymrRcg',
    appId: '1:1090632603312:ios:5f92377a2481cd1632cd75',
    messagingSenderId: '1090632603312',
    projectId: 'uninexus-1aea7',
    storageBucket: 'uninexus-1aea7.firebasestorage.app',
    iosBundleId: 'com.example.uninexus',
  );

}